# Generated by Django 4.2 on 2024-03-09 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('courier', 'کاربر پیک')], max_length=8)),
                ('condition', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='courier', to='user.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('customer', 'کاربر عادی')], max_length=8)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='user.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_long', models.FloatField(default=None)),
                ('origin_lat', models.FloatField(default=None)),
                ('destination_long', models.FloatField(default=None)),
                ('destination_lat', models.FloatField(default=None)),
                ('status', models.CharField(choices=[('waiting', 'منتظر قبول پبک'), ('the_way_to_pickup', 'پیک در راه مبدا'), ('the_way_to_deliver', 'پیک در راه مقصد'), ('delivered', 'انجام شد'), ('canceled', 'لغو شد')], default='waiting', max_length=30)),
                ('pick_date', models.DateTimeField(blank=True, null=True)),
                ('deliver_date', models.DateTimeField(blank=True, null=True)),
                ('condition', models.TextField(blank=True, null=True)),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.courier')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 - very bad'), (2, '2 - bad'), (3, '3 - avrage'), (4, '4 - good'), (5, '5 - excellent')], default='2 - bad')),
                ('comments', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(default=None)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.package')),
            ],
        ),
    ]
