# Generated by Django 4.2 on 2024-02-26 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_package_destination_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='destination_lat',
            field=models.DecimalField(decimal_places=6, default=datetime.datetime(2024, 2, 26, 8, 42, 21, 557466, tzinfo=datetime.timezone.utc), max_digits=9),
        ),
        migrations.AlterField(
            model_name='package',
            name='destination_long',
            field=models.DecimalField(decimal_places=6, default=datetime.datetime(2024, 2, 26, 8, 42, 21, 557466, tzinfo=datetime.timezone.utc), max_digits=9),
        ),
        migrations.AlterField(
            model_name='package',
            name='origin_lat',
            field=models.DecimalField(decimal_places=6, default=datetime.datetime(2024, 2, 26, 8, 42, 21, 557466, tzinfo=datetime.timezone.utc), max_digits=9),
        ),
        migrations.AlterField(
            model_name='package',
            name='origin_long',
            field=models.DecimalField(decimal_places=6, default=datetime.datetime(2024, 2, 26, 8, 42, 21, 557466, tzinfo=datetime.timezone.utc), max_digits=9),
        ),
    ]
