# Generated by Django 4.2 on 2024-02-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_alter_package_destination_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='registery_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 - very bad'), (2, '2 - bad'), (3, '3 - avrage'), (4, '4 - good'), (5, '5 - excellent')]),
        ),
        migrations.AlterField(
            model_name='package',
            name='deliver_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='package',
            name='pick_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('waiting', 'منتظر قبول پبک'), ('the_way_to_pickup', 'پیک در راه مبدا'), ('the_way_to_deliver', 'پیک در راه مقصد'), ('delivered', 'انجام شد'), ('canceled', 'لغو شد')], max_length=30),
        ),
    ]
