# Generated by Django 4.2 on 2024-02-26 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_alter_customer_registery_date_alter_feedback_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='condition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.courier'),
        ),
        migrations.AlterField(
            model_name='package',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.customer'),
        ),
        migrations.AlterField(
            model_name='package',
            name='deliver_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='pick_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('waiting', 'منتظر قبول پبک'), ('the_way_to_pickup', 'پیک در راه مبدا'), ('the_way_to_deliver', 'پیک در راه مقصد'), ('delivered', 'انجام شد'), ('canceled', 'لغو شد')], default='waiting', max_length=30),
        ),
    ]
