# Generated by Django 4.2 on 2024-03-04 18:02

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_courierrequest_user'),
        ('delivery', '0006_alter_package_condition_alter_package_courier_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courier',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='courier',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='customer',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='courier',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='courier',
            old_name='last_name',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='last_name',
            new_name='lastname',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='id',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='registery_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user_name',
        ),
        migrations.AddField(
            model_name='courier',
            name='customuser_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courier',
            name='type',
            field=models.CharField(choices=[('courier', 'کاربر پیک')], default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='customuser_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='type',
            field=models.CharField(choices=[('customer', 'کاربر عادی')], default=None, max_length=100),
            preserve_default=False,
        ),
    ]
