# Generated by Django 4.2 on 2024-03-04 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_courierrequest_user'),
        ('delivery', '0007_alter_courier_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courier',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.AlterModelManagers(
            name='courier',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='customer',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='courier',
            name='customuser_ptr',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='type',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customuser_ptr',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='type',
        ),
        migrations.AddField(
            model_name='courier',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courier',
            name='phone',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='phonenum', to='user.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='adress',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='adres', to='user.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='passw', to='user.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='phone', to='user.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='registery_date',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='register', to='user.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='user_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_name', to='user.customuser'),
            preserve_default=False,
        ),
    ]
