# Generated by Django 4.2 on 2024-03-05 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_alter_courier_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courier',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.AddField(
            model_name='courier',
            name='first_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='courier',
            name='last_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='courier',
            name='phone_number',
            field=models.CharField(default=None, max_length=12),
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default=None, max_length=12),
        ),
        migrations.AlterField(
            model_name='courier',
            name='condition',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='courier',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='adress',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='registery_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='comments',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 - very bad'), (2, '2 - bad'), (3, '3 - avrage'), (4, '4 - good'), (5, '5 - excellent')], default='2 - bad'),
        ),
        migrations.AlterField(
            model_name='package',
            name='condition',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='courier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.courier'),
        ),
        migrations.AlterField(
            model_name='package',
            name='customer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.customer'),
        ),
        migrations.AlterField(
            model_name='package',
            name='deliver_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='destination_lat',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='package',
            name='destination_long',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='package',
            name='origin_lat',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='package',
            name='origin_long',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='package',
            name='pick_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
