# Generated by Django 4.2 on 2024-03-05 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_courierrequest_user'),
        ('delivery', '0010_remove_courier_firstname_remove_courier_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='phone_number',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='phone', to='user.customuser'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='adress',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='adrs', to='user.customuser'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='passw', to='user.customuser'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='user.customuser'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='registery_date',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='rg_date', to='user.customuser'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='user.customuser'),
        ),
    ]
