# Generated by Django 4.2 on 2024-02-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customusermanager_alter_customuser_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUserManager',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='is_staff',
            new_name='is_courier',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_regular_user',
            field=models.BooleanField(default=False),
        ),
    ]
