# Generated by Django 4.2 on 2024-02-17 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_courier',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_regular_user',
        ),
    ]
