# Generated by Django 4.2 on 2024-02-25 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_courierrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courierrequest',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.customuser'),
        ),
    ]
